### ISSUE TITLE
Allow externalTrafficPolicy: local for Cluster type services with externalIP

### ISSUE THREAD

**Issue by xagent003** [kubernetes/kube-proxy#20]
Usecase: Bare metal env, no cloud provider or external LB. We have Kubevirt VMs that we want to front with a public IP. So we create a Service which will have just 1 endpoint (the VM/Pod), and assign it an externalIP. We don't care about advertising the service IP or Pod IP, as we plan to use Calico BGP to advertise the service's external IP.

Fails with the error:
```
The Service "netdebug4" is invalid: spec.externalTrafficPolicy: Invalid value: "Local": may only be set when `type` is 'NodePort' or 'LoadBalancer'
```
Here is our Service definition with an externalIP:

```
apiVersion: v1
kind: Service
metadata:
  name: netdebug4
spec:
  selector:
    vmService: vmcalicobridge2
  ports:
    - protocol: TCP
      port: 22
  externalTrafficPolicy: Local
  externalIPs:
    - 1.2.3.4
```

We use Calico BGP to advertise that (public IPs are part of the 1.2.3.0/24 block):
```
apiVersion: projectcalico.org/v3
kind: BGPConfiguration
metadata:
  creationTimestamp: null
  name: default
spec:
  asNumber: 64514
  logSeverityScreen: Debug
  nodeToNodeMeshEnabled: true
  serviceExternalIPs:
    - cidr: 1.2.3.0/24
```

we wanted externalTrafficPolicy=local
so that 1. the source IP is preserved and 2. to prevent an extra kube-proxy hop

the restriction here seems to come from k8s (cant create service with this set unless it is type Nodeport or Loadbalancer). I guess i'm trying to see why and dont understand what the difference is between an externalIP and an external Loadbalancer IP.

At the end of the day it is just some public IP associated with a Service - whether provided by an external cloud LB or just an externalIP that is routed down to the node (via Calico BGP).

Is there any way to achieve this?
